using System.Linq;
using System.Web.WebPages;
using SFA.DAS.Support.Portal.Web.Helpers;
using SFA.DAS.Support.Portal.Web.Models;
using SFA.DAS.Support.Portal.Web.ViewModels;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.Support.Portal.Web.Views.Account
{
#line 1 "..\..\Views\Account\PayeSchemes.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Account/PayeSchemes.cshtml")]
    public partial class _Views_Account_PayeSchemes_cshtml : System.Web.Mvc.WebViewPage<AccountDetailViewModel>
    {
        public _Views_Account_PayeSchemes_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\PayeSchemes.cshtml"
  
    ViewBag.modelTitle = Model.Account?.DasAccountName;
    ViewBag.accountId = Model.Account?.HashedAccountId;
    ViewBag.dateRegistered = Model.Account?.DateRegistered;
    ViewBag.currentSection = "account";
    ViewBag.currentPage = NavPages.PayeSchemes;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 11 "..\..\Views\Account\PayeSchemes.cshtml"
 if (Model.Account != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <h1>\r\n        PAYE Schemes\r\n    </h1>\r\n");

            
            #line 16 "..\..\Views\Account\PayeSchemes.cshtml"

    if (Model.Account.PayeSchemes != null && Model.Account.PayeSchemes.Any())
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>Added PAYE Schemes</p>\r\n");

            
            #line 20 "..\..\Views\Account\PayeSchemes.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <table");

WriteLiteral(" id=\"paye-schemes\"");

WriteLiteral(">\r\n            <tr>\r\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">PAYE Ref</th>\r\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Name</th>\r\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Date Added</th>\r\n            </tr>\r\n\r\n");

            
            #line 28 "..\..\Views\Account\PayeSchemes.cshtml"
            
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Account\PayeSchemes.cshtml"
             foreach (var payeScheme in Model.Account.PayeSchemes)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td");

WriteLiteral(" id=\"paye-ref\"");

WriteLiteral(">");

            
            #line 31 "..\..\Views\Account\PayeSchemes.cshtml"
                                 Write(payeScheme.Ref);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" id=\"paye-scheme-name\"");

WriteLiteral(">");

            
            #line 32 "..\..\Views\Account\PayeSchemes.cshtml"
                                         Write(payeScheme.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" id=\"paye-scheme-added-date\"");

WriteLiteral(">");

            
            #line 33 "..\..\Views\Account\PayeSchemes.cshtml"
                                               Write(AccountHelper.ConvertDateTimeToDdmmyyyyFormat(payeScheme.AddedDate));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");

            
            #line 35 "..\..\Views\Account\PayeSchemes.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n");

            
            #line 37 "..\..\Views\Account\PayeSchemes.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <p");

WriteLiteral(" id=\"no-paye-schemes-found\"");

WriteLiteral(">No PAYE schemes availables</p>\r\n");

            
            #line 41 "..\..\Views\Account\PayeSchemes.cshtml"
    }
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteLiteral(" id=\"no-account-found\"");

WriteLiteral(">Account not found</p>\r\n");

            
            #line 46 "..\..\Views\Account\PayeSchemes.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
