#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.DAS.Support.Portal.Web;
    using SFA.DAS.Support.Portal.Web.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/index.cshtml")]
    public partial class _Views_User_index_cshtml : System.Web.Mvc.WebViewPage<SFA.DAS.Support.Portal.Web.ViewModels.DetailViewModel>
    {
        public _Views_User_index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\User\index.cshtml"
  
    ViewBag.modelTitle = $"{Model.User.FirstName} {Model.User.LastName}";
    ViewBag.currentSection = "user";
    ViewBag.currentPage = "overview";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <h1>Overview</h1>\r\n\r\n");

            
            #line 10 "..\..\Views\User\index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\User\index.cshtml"
     if (Model.User != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <dl>\r\n\r\n            <dt>Name:</dt>\r\n            <dd>");

            
            #line 15 "..\..\Views\User\index.cshtml"
           Write(Model.User.FirstName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 15 "..\..\Views\User\index.cshtml"
                                 Write(Model.User.LastName);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n\r\n            <dt>Email:</dt>\r\n            <dd><a");

WriteAttribute("href", Tuple.Create(" href=\"", 445), Tuple.Create("\"", 476)
, Tuple.Create(Tuple.Create("", 452), Tuple.Create("mailto:", 452), true)
            
            #line 19 "..\..\Views\User\index.cshtml"
, Tuple.Create(Tuple.Create("", 459), Tuple.Create<System.Object, System.Int32>(Model.User.Email
            
            #line default
            #line hidden
, 459), false)
);

WriteLiteral(">");

            
            #line 19 "..\..\Views\User\index.cshtml"
                                              Write(Model.User.Email);

            
            #line default
            #line hidden
WriteLiteral("</a></dd>\r\n\r\n            <dt>Status:</dt>\r\n            <dd>");

            
            #line 22 "..\..\Views\User\index.cshtml"
           Write(Model.User.Status);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        </dl>\r\n");

            
            #line 25 "..\..\Views\User\index.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>User not found</p>\r\n");

            
            #line 29 "..\..\Views\User\index.cshtml"
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
