using System.Linq;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;
using SFA.DAS.Portal.Web.ViewModels;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.Portal.Web.Views.Search
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Search/Index.cshtml")]
    public partial class _Views_Search_Index_cshtml : System.Web.Mvc.WebViewPage<SearchResultsViewModel>
    {
        public _Views_Search_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Search\Index.cshtml"
  
    ViewBag.currentSection = "search";
    ViewBag.currentPage = "users";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Search for a user</h1>\r\n");

            
            #line 8 "..\..\Views\Search\Index.cshtml"
 using (Html.BeginForm("Index", "Search", FormMethod.Get, new { accept_charset = "utf-8", @class = "search-field", role = "search" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" for=\"search-main\"");

WriteLiteral(">\r\n                    \r\n        </label>\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Search\Index.cshtml"
   Write(Html.TextBoxFor(m => m.SearchTerm, string.Empty, new { id = "search-main", type = "search", @class = "form-control", placeholder = "Enter a name or email address", required = "required", maxlength = "100" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"Page\"");

WriteLiteral(" value=\"1\"");

WriteLiteral("/>\r\n        <div");

WriteLiteral(" class=\"search-submit\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">Search</button>\r\n        </div>\r\n    </div>\r\n");

            
            #line 20 "..\..\Views\Search\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 22 "..\..\Views\Search\Index.cshtml"
 if (!string.IsNullOrEmpty(Model.SearchTerm))
{

            
            #line default
            #line hidden
WriteLiteral("    <p>");

            
            #line 24 "..\..\Views\Search\Index.cshtml"
  Write(Html.ActionLink("Clear search", "Index"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 25 "..\..\Views\Search\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 27 "..\..\Views\Search\Index.cshtml"
 if (!Model.Results.Any() && Model.Page > 1)
{

            
            #line default
            #line hidden
WriteLiteral("    <p>There are no more results.</p>\r\n");

            
            #line 30 "..\..\Views\Search\Index.cshtml"
}
else if (!string.IsNullOrEmpty(Model.ErrorMessage))
{

            
            #line default
            #line hidden
WriteLiteral("    <p>");

            
            #line 33 "..\..\Views\Search\Index.cshtml"
  Write(Model.ErrorMessage);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 34 "..\..\Views\Search\Index.cshtml"
}
else if (Model.Results != null && Model.Results.Any())
{

            
            #line default
            #line hidden
WriteLiteral("    <table>\r\n        <tr>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Name</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Email</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Accounts</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Status</th>\r\n        </tr>\r\n");

            
            #line 44 "..\..\Views\Search\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Search\Index.cshtml"
         foreach (var item in Model.Results)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 48 "..\..\Views\Search\Index.cshtml"
               Write(Html.ActionLink($"{item.FirstName} {item.LastName}", "Detail", new {id = item.Id, searchTerm = Model.SearchTerm}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 51 "..\..\Views\Search\Index.cshtml"
               Write(item.Email);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

            
            #line 54 "..\..\Views\Search\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Search\Index.cshtml"
                     if (item.Accounts != null && item.Accounts.Any())
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <ul");

WriteLiteral(" class=\"list\"");

WriteLiteral(">\r\n");

            
            #line 57 "..\..\Views\Search\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Search\Index.cshtml"
                             foreach (var account in item.Accounts)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n");

WriteLiteral("                                    ");

            
            #line 60 "..\..\Views\Search\Index.cshtml"
                               Write(Html.ActionLink(account.DasAccountName, "Index", "Account", new { id = account.HashedAccountId }, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </li>\r\n");

            
            #line 62 "..\..\Views\Search\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n");

            
            #line 64 "..\..\Views\Search\Index.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <span>NA</span>\r\n");

            
            #line 68 "..\..\Views\Search\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 71 "..\..\Views\Search\Index.cshtml"
               Write(item.Status);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n");

            
            #line 74 "..\..\Views\Search\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </table>\r\n");

            
            #line 76 "..\..\Views\Search\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n\r\n");

            
            #line 79 "..\..\Views\Search\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Search\Index.cshtml"
         if (Model.Page > 1)
        {
            
            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\Search\Index.cshtml"
       Write(Html.ActionLink("< Prev", "Index", new {Model.SearchTerm, Page = Model.Page - 1}, new {@class = "previous"}));

            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\Search\Index.cshtml"
                                                                                                                         
            ;
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 85 "..\..\Views\Search\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 85 "..\..\Views\Search\Index.cshtml"
         if (Model.Results.Any() && Model.Page != Model.LastPage)
        {
            
            
            #line default
            #line hidden
            
            #line 87 "..\..\Views\Search\Index.cshtml"
       Write(Html.ActionLink("Next >", "Index", new {Model.SearchTerm, Page = Model.Page + 1}, new {@class = "next"}));

            
            #line default
            #line hidden
            
            #line 87 "..\..\Views\Search\Index.cshtml"
                                                                                                                     
            ;
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 91 "..\..\Views\Search\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Search\Index.cshtml"
         if (Model.Page != 1 && Model.LastPage != 1)
        {

            
            #line default
            #line hidden
WriteLiteral("            <span>Page ");

            
            #line 93 "..\..\Views\Search\Index.cshtml"
                  Write(Model.Page);

            
            #line default
            #line hidden
WriteLiteral(" of ");

            
            #line 93 "..\..\Views\Search\Index.cshtml"
                                 Write(Model.LastPage);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 94 "..\..\Views\Search\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 97 "..\..\Views\Search\Index.cshtml"
}
else if (Model.NewResults != null && Model.NewResults.Any())
{
    foreach (var item in Model.NewResults)
    {
        
            
            #line default
            #line hidden
            
            #line 102 "..\..\Views\Search\Index.cshtml"
   Write(Html.Raw(item));

            
            #line default
            #line hidden
            
            #line 102 "..\..\Views\Search\Index.cshtml"
                       
    }
}
else if(!Model.Results.Any() && !string.IsNullOrEmpty(Model.SearchTerm))
{

            
            #line default
            #line hidden
WriteLiteral("    <p>No user found</p>\r\n");

            
            #line 108 "..\..\Views\Search\Index.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
