using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.Support.Portal.Web.Views.Home
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
   
    ViewBag.currentSection = "search";
    ViewBag.currentPage = "users";

            
            #line default
            #line hidden
WriteLiteral("\n\n<h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Search for a user</h1>\n");

            
            #line 7 "..\..\Views\Home\Index.cshtml"
 using (Html.BeginForm("Index", "Search", FormMethod.Get, new { @class = "search-field" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(">\n        <label");

WriteLiteral(" for=\"search-main\"");

WriteLiteral(">\n                    \n        </label>\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\Home\Index.cshtml"
   Write(Html.TextBox("SearchTerm", string.Empty, new { id = "search-main", type = "search", @class = "form-control", placeholder = "Enter a name or email address", required="required", maxlength="100" }));

            
            #line default
            #line hidden
WriteLiteral("\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"Page\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" />\n        <div");

WriteLiteral(" class=\"search-submit\"");

WriteLiteral(">\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">Search</button>\n        </div>\n    </div>\n");

            
            #line 19 "..\..\Views\Home\Index.cshtml"
}      

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
