#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Sfa.Das.Console.Web;
    using Sfa.Das.Console.Web.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/UIFinanceCredit.cshtml")]
    public partial class _Views_Home_UIFinanceCredit_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_UIFinanceCredit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\UIFinanceCredit.cshtml"
  
    ViewBag.modelTitle = "ABC Midlands";
    ViewBag.accountId = "A1B2C";
    ViewBag.currentSection = "account";
    ViewBag.currentPage = "finance";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Credit Details</h1>\r\n<p");

WriteLiteral(" class=\"lede\"");

WriteLiteral(">Credit made on 1 Mar 2017.</p>\r\n\r\n<table>\r\n    <thead>\r\n        <tr>\r\n          " +
"  <th");

WriteLiteral(" id=\"th-ps\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">PAYE scheme</th>\r\n            <th");

WriteLiteral(" id=\"th-ld\"");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Levy paid to HMRC</th>\r\n            <th");

WriteLiteral(" id=\"th-ef\"");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">English %</th>\r\n            <th");

WriteLiteral(" id=\"th-tu\"");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">10% Top up</th>\r\n            <th");

WriteLiteral(" id=\"th-pi\"");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Paid in</th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n        <tr");

WriteLiteral(" class=\"responsive-tr\"");

WriteLiteral(">\r\n            <td");

WriteLiteral(" headers=\"th-ps\"");

WriteLiteral(">\r\n                <span>777/AA00001</span>\r\n            </td>\r\n            <td");

WriteLiteral(" headers=\"th-ld\"");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(">\r\n                £10,000.00\r\n            </td>\r\n            <td");

WriteLiteral(" headers=\"th-ef\"");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(">\r\n                90.00%\r\n            </td>\r\n            <td");

WriteLiteral(" headers=\"th-tu\"");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(">\r\n                £900.00\r\n            </td>\r\n            <td");

WriteLiteral(" headers=\"th-pi\"");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(">\r\n                £9,900.00\r\n            </td>\r\n        </tr>\r\n        <tr");

WriteLiteral(" class=\"total\"");

WriteLiteral(">\r\n            <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" id=\"th-total\"");

WriteLiteral("><span");

WriteLiteral(" class=\"vh\"");

WriteLiteral(">Total</span></th>\r\n            <td");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(" headers=\"th-total\"");

WriteLiteral(">£9,900.00</td>\r\n        </tr>\r\n    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
