#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Sfa.Das.Console.Web;
    using Sfa.Das.Console.Web.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/UIFinancePayment.cshtml")]
    public partial class _Views_Home_UIFinancePayment_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_UIFinancePayment_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\UIFinancePayment.cshtml"
  
    ViewBag.modelTitle = "ABC Midlands";
    ViewBag.accountId = "A1B2C";
    ViewBag.currentSection = "account";
    ViewBag.currentPage = "finance";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Payment details</h1>\r\n\r\n<dl>\r\n    <dt>Date</dt>\r\n    <dd>4 may 2017</dd>\r\n    <d" +
"t>Payment to</dt>\r\n    <dd>Active Learning &amp; Development Limited</dd>\r\n</dl>" +
"\r\n\r\n<table");

WriteLiteral(" class=\"responsive\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" colspan=\"2\"");

WriteLiteral("></th>\r\n            <th");

WriteLiteral(" class=\"highlight colgroup\"");

WriteLiteral(" scope=\"colgroup\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">Co-investment</th>\r\n            <th");

WriteLiteral(" colspan=\"2\"");

WriteLiteral("></th>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"tw-20\"");

WriteLiteral(">Course</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"numeric tw-20\"");

WriteLiteral(">Paid from levy</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"numeric tw-20 highlight\"");

WriteLiteral(">Government contribution</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"numeric tw-20 highlight\"");

WriteLiteral(">Employer contribution</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"numeric tw-15\"");

WriteLiteral(">Amount</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"tw-5\"");

WriteLiteral("><span");

WriteLiteral(" class=\"vh\"");

WriteLiteral(">Action</span></th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n        <tr>\r\n    " +
"        <td");

WriteLiteral(" data-label=\"Course\"");

WriteLiteral(">Writing <span");

WriteLiteral(" class=\"no-wrap\"");

WriteLiteral(">level 1</span></td>\r\n            <td");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(" data-label=\"Paid from levy\"");

WriteLiteral(">-£970</td>\r\n            <td");

WriteLiteral(" class=\"numeric highlight\"");

WriteLiteral(" data-label=\"Government contribution\"");

WriteLiteral(">£0</td>\r\n            <td");

WriteLiteral(" class=\"numeric highlight\"");

WriteLiteral(" data-label=\"Your contribution\"");

WriteLiteral(">£0</td>\r\n            <td");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(" data-label=\"Amount\"");

WriteLiteral(">-£970</td>\r\n            <td><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Details</a></td>\r\n        </tr>\r\n    </tbody>\r\n    <tfoot>\r\n        <tr");

WriteLiteral(" class=\"total\"");

WriteLiteral(">\r\n            <td");

WriteLiteral(" data-label=\"Totals\"");

WriteLiteral("> </td>\r\n            <td");

WriteLiteral(" data-label=\"Paid from levy\"");

WriteLiteral(" class=\"total numeric no-wrap\"");

WriteLiteral(">-£970</td>\r\n            <td");

WriteLiteral(" data-label=\"Government contribution\"");

WriteLiteral(" class=\"highlight total numeric no-wrap\"");

WriteLiteral(">£0</td>\r\n            <td");

WriteLiteral(" data-label=\"Your contribution\"");

WriteLiteral(" class=\"highlight total numeric no-wrap\"");

WriteLiteral(">£0</td>\r\n            <td");

WriteLiteral(" data-label=\"Amount\"");

WriteLiteral(" class=\"total numeric no-wrap\"");

WriteLiteral(">-£970</td>\r\n            <td></td>\r\n        </tr>\r\n    </tfoot>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
