#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Sfa.Das.Console.Web;
    using Sfa.Das.Console.Web.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/UIFinanceAuth.cshtml")]
    public partial class _Views_Home_UIFinanceAuth_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_UIFinanceAuth_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\UIFinanceAuth.cshtml"
  
    ViewBag.modelTitle = "ABC Midlands";
    ViewBag.accountId = "A1B2C";
    ViewBag.currentSection = "account";
    ViewBag.currentPage = "finance";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Finance</h1>\r\n<p");

WriteLiteral(" class=\"lede\"");

WriteLiteral(">Enter the following information to verify the caller\'s identity</p>\r\n<form");

WriteLiteral(" method=\"POST\"");

WriteLiteral(" action=\"\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"form-label\"");

WriteLiteral(" for=\"\"");

WriteLiteral(">3rd &amp; 4th characters of a PAYE scheme</label>\r\n        <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" maxlength=\"2\"");

WriteLiteral(">\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"form-label\"");

WriteLiteral(" for=\"\"");

WriteLiteral(">\r\n            Current levy balance \r\n            <span");

WriteLiteral(" class=\"form-hint\"");

WriteLiteral(">Excluding pence e.g. 11003</span>\r\n        </label>\r\n        <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" />\r\n    </div>\r\n</form>\r\n");

        }
    }
}
#pragma warning restore 1591
