using System.Globalization;
using System.Linq;
using System.Web.WebPages;
using SFA.DAS.Portal.Web.Models;
using SFA.DAS.Portal.Web.ViewModels;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.Portal.Web.Views.Account
{
#line 1 "..\..\Views\Account\Finance.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Account/Finance.cshtml")]
    public partial class _Views_Account_Finance_cshtml : System.Web.Mvc.WebViewPage<FinanceViewModel>
    {
        public _Views_Account_Finance_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\Finance.cshtml"
  
    ViewBag.modelTitle = Model.Account.DasAccountName;
    ViewBag.accountId = Model.Account.HashedAccountId;
    ViewBag.dateRegistered = Model.Account.DateRegistered;
    ViewBag.currentSection = "account";
    ViewBag.currentPage = NavPages.Finance;
    ViewBag.payeSchemes = Model.Account.PayeSchemes;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 12 "..\..\Views\Account\Finance.cshtml"
  
    var culture = new CultureInfo("en-GB");

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 16 "..\..\Views\Account\Finance.cshtml"
 if (Model.Account != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Finance</h1>\r\n");

            
            #line 19 "..\..\Views\Account\Finance.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"data-wrap\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"data\"");

WriteLiteral(">\r\n            <dl>\r\n                <dt>Current funds</dt>\r\n                <dd>" +
"");

            
            #line 24 "..\..\Views\Account\Finance.cshtml"
               Write(Model.Balance.ToString("C2", culture));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n            </dl>\r\n        </div>\r\n    </div>\r\n");

            
            #line 28 "..\..\Views\Account\Finance.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <h2>Transactions</h2>\r\n");

            
            #line 30 "..\..\Views\Account\Finance.cshtml"

    if (Model.Account.Transactions.Any())
    {

            
            #line default
            #line hidden
WriteLiteral("        <table>\r\n            <tr>\r\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Payment date</th>\r\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Description</th>\r\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Amount</th>\r\n            </tr>\r\n");

            
            #line 39 "..\..\Views\Account\Finance.cshtml"
            
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Account\Finance.cshtml"
             foreach (var item in Model.Account.Transactions)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td");

WriteLiteral(" id=\"transactionPaymentDate\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 43 "..\..\Views\Account\Finance.cshtml"
                   Write(item.DateCreated.ToString("dd/MM/yyyy"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td");

WriteLiteral(" id=\"transactionDescription\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 46 "..\..\Views\Account\Finance.cshtml"
                   Write(item.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td");

WriteLiteral(" id=\"transactionAmount\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 49 "..\..\Views\Account\Finance.cshtml"
                   Write(item.Amount.ToString("C2", culture));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n");

            
            #line 52 "..\..\Views\Account\Finance.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n");

            
            #line 54 "..\..\Views\Account\Finance.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>There are no transactions for this account</p>\r\n");

            
            #line 58 "..\..\Views\Account\Finance.cshtml"
    }
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <p>Account not found</p>\r\n");

            
            #line 63 "..\..\Views\Account\Finance.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
