using System.Web.WebPages;
using SFA.DAS.Portal.Web.Models;
using SFA.DAS.Portal.Web.ViewModels;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.Portal.Web.Views.Account
{
#line 1 "..\..\Views\Account\Index.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Account/Index.cshtml")]
    public partial class _Views_Account_Index_cshtml : System.Web.Mvc.WebViewPage<AccountDetailViewModel>
    {
        public _Views_Account_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\Index.cshtml"
  
    ViewBag.modelTitle = Model.Account.DasAccountName;
    ViewBag.accountId = Model.Account.HashedAccountId;
    ViewBag.dateRegistered = Model.Account.DateRegistered;
    ViewBag.currentSection = "account";
    ViewBag.currentPage = NavPages.Overview;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 11 "..\..\Views\Account\Index.cshtml"
 if (Model.Account != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <h1>\r\n        Organisations\r\n    </h1>\r\n");

            
            #line 16 "..\..\Views\Account\Index.cshtml"
    foreach (var organisation in Model.Account.LegalEntities)
    {

            
            #line default
            #line hidden
WriteLiteral("        <dl>\r\n\r\n            <dt>Name:</dt>\r\n            <dd>");

            
            #line 21 "..\..\Views\Account\Index.cshtml"
           Write(organisation.Name);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n            <dt>Address:</dt>\r\n            <dd>");

            
            #line 24 "..\..\Views\Account\Index.cshtml"
           Write(organisation.Address);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n            <dt>Source:</dt>\r\n            <dd>");

            
            #line 27 "..\..\Views\Account\Index.cshtml"
           Write(organisation.Source);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n        </dl>\r\n");

            
            #line 29 "..\..\Views\Account\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <hr/>\r\n");

            
            #line 31 "..\..\Views\Account\Index.cshtml"
    }
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <p>Account not found</p>\r\n");

            
            #line 36 "..\..\Views\Account\Index.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
