#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Sfa.Das.Console.Web;
    using Sfa.Das.Console.Web.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/UIFinance.cshtml")]
    public partial class _Views_Home_UIFinance_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_UIFinance_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\UIFinance.cshtml"
  
    ViewBag.modelTitle = "ABC Midlands";
    ViewBag.accountId = "A1B2C";
    ViewBag.currentSection = "account";
    ViewBag.currentPage = "finance";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Finance</h1>\r\n\r\n<div");

WriteLiteral(" class=\"data-wrap\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"data\"");

WriteLiteral(">\r\n        <dl>\r\n            <dt>Current funds</dt>\r\n            <dd");

WriteLiteral(" class=\"\"");

WriteLiteral(">£0</dd>\r\n        </dl>\r\n    </div>\r\n</div>\r\n\r\n<table>\r\n    <thead>\r\n        <tr>" +
"\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Payment date</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Description</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Amount</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral("><span");

WriteLiteral(" class=\"vh\"");

WriteLiteral(">Action</span></th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n        <tr>\r\n    " +
"        <td>07/11/2017</td>\r\n            <td>Training provider</td>\r\n           " +
" <td><span");

WriteLiteral(" class=\"no-wrap\"");

WriteLiteral(">-£12,000.00</span></td>\r\n            <td><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Details <span");

WriteLiteral(" class=\"vh\"");

WriteLiteral(">about the transaction to Training Provider</span></a></td>\r\n        </tr>\r\n     " +
"   <tr>\r\n            <td>07/11/2017</td>\r\n            <td>Training provider</td>" +
"\r\n            <td><span");

WriteLiteral(" class=\"no-wrap\"");

WriteLiteral(">-£12,000.00</span></td>\r\n            <td><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Details <span");

WriteLiteral(" class=\"vh\"");

WriteLiteral(">about the transaction to Training Provider</span></a></td>\r\n        </tr>\r\n     " +
"   <tr>\r\n            <td>07/11/2017</td>\r\n            <td>Training provider</td>" +
"\r\n            <td><span");

WriteLiteral(" class=\"no-wrap\"");

WriteLiteral(">-£12,000.00</span></td>\r\n            <td><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Details <span");

WriteLiteral(" class=\"vh\"");

WriteLiteral(">about the transaction to Training Provider</span></a></td>\r\n        </tr>\r\n     " +
"   <tr>\r\n            <td>07/11/2017</td>\r\n            <td>Training provider</td>" +
"\r\n            <td><span");

WriteLiteral(" class=\"no-wrap\"");

WriteLiteral(">-£12,000.00</span></td>\r\n            <td><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Details <span");

WriteLiteral(" class=\"vh\"");

WriteLiteral(">about the transaction to Training Provider</span></a></td>\r\n        </tr>\r\n     " +
"   <tr>\r\n            <td>07/11/2017</td>\r\n            <td>Training provider</td>" +
"\r\n            <td><span");

WriteLiteral(" class=\"no-wrap\"");

WriteLiteral(">-£12,000.00</span></td>\r\n            <td><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Details <span");

WriteLiteral(" class=\"vh\"");

WriteLiteral(">about the transaction to Training Provider</span></a></td>\r\n        </tr>\r\n     " +
"   <tr>\r\n            <td>07/11/2017</td>\r\n            <td>Training provider</td>" +
"\r\n            <td><span");

WriteLiteral(" class=\"no-wrap\"");

WriteLiteral(">-£12,000.00</span></td>\r\n            <td><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Details <span");

WriteLiteral(" class=\"vh\"");

WriteLiteral(">about the transaction to Training Provider</span></a></td>\r\n        </tr>\r\n    <" +
"/tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
