using System;
using System.Web.Mvc.Html;
using System.Web.WebPages;
using SFA.DAS.Portal.Web.Helpers;
using SFA.DAS.Portal.Web.Models;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.Portal.Web.Views.Challenge
{
#line 1 "..\..\Views\Challenge\Index.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Challenge/Index.cshtml")]
    public partial class _Views_Challenge_Index_cshtml : System.Web.Mvc.WebViewPage<ChallengeViewModel>
    {

#line 44 "..\..\Views\Challenge\Index.cshtml"
public System.Web.WebPages.HelperResult ShowErrorMessage()
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 45 "..\..\Views\Challenge\Index.cshtml"
 
    if (Model.HasError)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"error-summary\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            <p>Incorrect information entered.</p>\r\n        </div>\r\n");


#line 51 "..\..\Views\Challenge\Index.cshtml"

    }


#line default
#line hidden
});

#line 53 "..\..\Views\Challenge\Index.cshtml"
}
#line default
#line hidden

        public _Views_Challenge_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Challenge\Index.cshtml"
  
    ViewBag.modelTitle = Model.Account.DasAccountName;
    ViewBag.accountId = Model.Account.HashedAccountId;
    ViewBag.dateRegistered = Model.Account.DateRegistered;
    ViewBag.currentSection = "account";
    ViewBag.currentPage = NavPages.Challenge;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 12 "..\..\Views\Challenge\Index.cshtml"
Write(ShowErrorMessage());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1>Finance</h1>\r\n\r\n");

            
            #line 16 "..\..\Views\Challenge\Index.cshtml"
   Html.BeginForm(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <p");

WriteLiteral(" class=\"lede\"");

WriteLiteral(">Enter the following information to verify the caller\'s identity:</p>\r\n\r\n    <inp" +
"ut");

WriteLiteral(" name=\"url\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 530), Tuple.Create("\"", 548)
            
            #line 20 "..\..\Views\Challenge\Index.cshtml"
, Tuple.Create(Tuple.Create("", 538), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 538), false)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" name=\"id\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 588), Tuple.Create("\"", 605)
            
            #line 21 "..\..\Views\Challenge\Index.cshtml"
, Tuple.Create(Tuple.Create("", 596), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 596), false)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" name=\"firstCharacterPosition\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 665), Tuple.Create("\"", 693)
            
            #line 22 "..\..\Views\Challenge\Index.cshtml"
, Tuple.Create(Tuple.Create("", 673), Tuple.Create<System.Object, System.Int32>(Model.Characters[0]
            
            #line default
            #line hidden
, 673), false)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" name=\"secondCharacterPosition\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 754), Tuple.Create("\"", 782)
            
            #line 23 "..\..\Views\Challenge\Index.cshtml"
, Tuple.Create(Tuple.Create("", 762), Tuple.Create<System.Object, System.Int32>(Model.Characters[1]
            
            #line default
            #line hidden
, 762), false)
);

WriteLiteral(" />\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"form-label\"");

WriteLiteral(" for=\"challenge1\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\Challenge\Index.cshtml"
                                              Write(ChallengeHelper.GetChallengeMessage(Model.Characters));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <input");

WriteLiteral(" class=\"form-control single-char focus-switch\"");

WriteLiteral(" name=\"challenge1\"");

WriteLiteral(" id=\"challenge1\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" maxlength=\"1\"");

WriteLiteral(" data-next-id=\"challenge2\"");

WriteLiteral(" />\r\n        <input");

WriteLiteral(" class=\"form-control single-char focus-switch\"");

WriteLiteral(" name=\"challenge2\"");

WriteLiteral(" id=\"challenge2\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" maxlength=\"1\"");

WriteLiteral(" data-next-id=\"balance\"");

WriteLiteral(" />\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"form-label\"");

WriteLiteral(" for=\"balance\"");

WriteLiteral(">\r\n            Current levy balance (excluding pence):\r\n        </label>\r\n       " +
" <input");

WriteLiteral(" name=\"balance\"");

WriteLiteral(" id=\"balance\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control form-control-1-4\"");

WriteLiteral(" />\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button\"");

WriteLiteral(" />\r\n    </div>\r\n\r\n");

            
            #line 42 "..\..\Views\Challenge\Index.cshtml"
   Html.EndForm(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
