#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.DAS.Support.Portal.Web;
    using SFA.DAS.Support.Portal.Web.Models;
    
    #line 1 "..\..\Views\Search\Index.cshtml"
    using SFA.DAS.Support.Shared.SearchIndexModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Search/Index.cshtml")]
    public partial class _Views_Search_Index_cshtml : System.Web.Mvc.WebViewPage<SFA.DAS.Support.Portal.Web.ViewModels.SearchResultsViewModel>
    {
        public _Views_Search_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Search\Index.cshtml"
  
    /**/

    ViewBag.currentSection = "search";
    ViewBag.currentPage = "users";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<style>\r\n    .form-label {\r\n        display: inline-block !important;\r\n    }\r" +
"\n</style>\r\n\r\n<div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n\r\n        <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Search</h1>\r\n");

            
            #line 20 "..\..\Views\Search\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Search\Index.cshtml"
         using (Html.BeginForm("Index", "Search", FormMethod.Get, new { accept_charset = "utf-8", @class = "search-field", role = "search" }))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"search-main\"");

WriteLiteral(">\r\n                </label>\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Search\Index.cshtml"
           Write(Html.TextBoxFor(m => m.SearchTerm, string.Empty, new { id = "search-main", type = "search", @class = "form-control", placeholder = "Enter a name or email address", required = "required", maxlength = "100" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"Page\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" />\r\n                <div");

WriteLiteral(" class=\"search-submit\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">Search</button>\r\n                </div>\r\n            </div>\r\n");

            
            #line 31 "..\..\Views\Search\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <fieldset>\r\n                    <label");

WriteLiteral(" for=\"UserSearchCategory\"");

WriteLiteral(" class=\"form-label selection-button-radio form-control-1-4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"SearchType\"");

WriteLiteral(" id=\"UserSearchCategory\"");

WriteLiteral(" checked");

WriteAttribute("value", Tuple.Create(" value=\"", 1399), Tuple.Create("\"", 1427)
            
            #line 35 "..\..\Views\Search\Index.cshtml"
                     , Tuple.Create(Tuple.Create("", 1407), Tuple.Create<System.Object, System.Int32>(SearchCategory.User
            
            #line default
            #line hidden
, 1407), false)
);

WriteLiteral(">\r\n                        Users\r\n                    </label>\r\n\r\n               " +
"     <label");

WriteLiteral(" for=\"AccountSearchCategory\"");

WriteLiteral(" class=\"form-label selection-button-radio form-control-1-4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"SearchType\"");

WriteLiteral(" id=\"AccountSearchCategory\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1698), Tuple.Create("\"", 1729)
            
            #line 40 "..\..\Views\Search\Index.cshtml"
                , Tuple.Create(Tuple.Create("", 1706), Tuple.Create<System.Object, System.Int32>(SearchCategory.Account
            
            #line default
            #line hidden
, 1706), false)
);

WriteLiteral(">\r\n                        Accounts\r\n                    </label>\r\n              " +
"  </fieldset>\r\n            </div>\r\n");

            
            #line 45 "..\..\Views\Search\Index.cshtml"

        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n</div>\r\n\r\n\r\n\r\n");

            
            #line 54 "..\..\Views\Search\Index.cshtml"
 if (Model.AccountSearchResults != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");

WriteLiteral("    <br />\r\n");

            
            #line 58 "..\..\Views\Search\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n            <h2> Results</h2>\r\n            <p>  ");

            
            #line 62 "..\..\Views\Search\Index.cshtml"
            Write(Model.TotalAccountSearchItems);

            
            #line default
            #line hidden
WriteLiteral(" accounts found</p>\r\n        </div>\r\n    </div>\r\n");

            
            #line 65 "..\..\Views\Search\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n            <table>\r\n                <tr>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Account</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Account ID</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral("></th>\r\n                </tr>\r\n");

            
            #line 75 "..\..\Views\Search\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Search\Index.cshtml"
                 foreach (var account in Model.AccountSearchResults)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 79 "..\..\Views\Search\Index.cshtml"
                       Write(account.Account);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 82 "..\..\Views\Search\Index.cshtml"
                       Write(account.AccountID);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 85 "..\..\Views\Search\Index.cshtml"
                       Write(Html.ActionLink("view", "Index", "Account", new { id = account.AccountID }, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");

            
            #line 88 "..\..\Views\Search\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </table>\r\n\r\n            <div");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n\r\n");

            
            #line 93 "..\..\Views\Search\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 93 "..\..\Views\Search\Index.cshtml"
                 if (Model.Page > 1)
                {
                    
            
            #line default
            #line hidden
            
            #line 95 "..\..\Views\Search\Index.cshtml"
               Write(Html.ActionLink("< Prev", "Index", new { Model.SearchTerm, Page = Model.Page - 1 }, new { @class = "previous" }));

            
            #line default
            #line hidden
            
            #line 95 "..\..\Views\Search\Index.cshtml"
                                                                                                                                     

                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 99 "..\..\Views\Search\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 99 "..\..\Views\Search\Index.cshtml"
                 if (Model.AccountSearchResults.Any() && Model.Page != Model.LastPage)
                {
                    
            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Search\Index.cshtml"
               Write(Html.ActionLink("Next >", "Index", new { Model.SearchTerm, Page = Model.Page + 1 }, new { @class = "next" }));

            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Search\Index.cshtml"
                                                                                                                                 

                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 105 "..\..\Views\Search\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Search\Index.cshtml"
                 if (Model.Page != 1 && Model.LastPage != 1)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span>Page ");

            
            #line 107 "..\..\Views\Search\Index.cshtml"
                          Write(Model.Page);

            
            #line default
            #line hidden
WriteLiteral(" of ");

            
            #line 107 "..\..\Views\Search\Index.cshtml"
                                         Write(Model.LastPage);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 108 "..\..\Views\Search\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n\r\n        </div>\r\n\r\n    </div>\r\n");

            
            #line 116 "..\..\Views\Search\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
